### ISSUE TITLE
これをwatchする

### ISSUE THREAD

**Issue by techfeed-github** [dsuket/tf-gh-subscribe-test#5]
# Angular
https://github.com/angular/in-memory-web-api
https://github.com/angular/protractor
https://github.com/angular/angularfire
https://github.com/angular/angular.js
https://github.com/angular/universal
https://github.com/angular/ngcc-validation
https://github.com/angular/components
https://github.com/angular/flex-layout
https://github.com/angular/angular
https://github.com/angular/angular-cli
https://github.com/ionic-team/ionic
https://github.com/NativeScript/NativeScript
# React
https://github.com/facebook/react
https://github.com/facebook/create-react-app
https://github.com/facebook/react-native
https://github.com/facebook/flow
https://github.com/facebook/relay
https://github.com/facebook/draft-js
https://github.com/facebook/componentkit
https://github.com/facebook/react-360
https://github.com/facebook/react-native-fbsdk
https://github.com/zeit/next.js
https://github.com/ionic-team/ionic
https://github.com/enaqx/awesome-react
https://github.com/preactjs/preact
https://github.com/jondot/awesome-react-native

**Comment by nao5151** [comment]
done
